### ISSUE TITLE
Improve Sample Data

### ISSUE THREAD

**Issue by nilopmsft** [JWStarkie/PurviewAccelerator#40]
**Is your feature request related to a problem? Please describe.**
Sample data for CreditCardInfo contains a credit card number that is provided in scientific form.

Example:
4.93648E+17

**Describe the solution you'd like**
Would be beneficial to have 'valid' credit card numbers that would be classified by Purview to demonstrate classification further.
Purview does require the credit card number to pass a Luhn test in order to classify, more information on the pattern here. Seems as though potentially renaming the column could help as well.
https://docs.microsoft.com/en-us/azure/purview/supported-classifications#credit-card-number

**Describe alternatives you've considered**
Do recognize there are other classifications found such as IP address or email but the more the merrier. This would just make the data more rich. The [Bogus Library](https://github.com/bchavez/Bogus) could help.

**Comment by JWStarkie** [comment]
Thank you for pointing this our @nilopmsft 😊 we'll look into fixing this asap.
